version: "3.7"
services:
  mydict:
    build: ./docker/mydict
    volumes:
      - dict-volume:/var/lib/mecab/dic/mydic
  webapp:
    build:
      context: ./webapp
      dockerfile: ../docker/webapp/Dockerfile
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    volumes:
      - ./webapp:/usr/src/app
      - ./data/webapp/:/data
      - dict-volume:/var/lib/mecab/dic/mydic
    ports:
      - "8088:8088"
    user: $UID:$GID
    links:
      - elasticsearch
      - fluentd
    depends_on:
      - elasticsearch
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "onsen-compo.app"
    environment:
      RUST_LOG_STYLE: never
      RUST_LOG: debug
    entrypoint: /bin/bash
    command: "-i"
    #entrypoint: /usr/local/cargo/bin/cargo
    #command: "run app"
    tty: true
  elasticsearch:
    build: docker/elasticsearch
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  nginx:
    image: nginx:1-alpine
    ports:
      - "8080:80"
    links:
      - webapp
      - fluentd
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
  fluentd:
    build: ./docker/fluentd
    volumes:
      - ./docker/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  kibana:
    image: kibana:7.6.2
    links:
      - elasticsearch
    ports:
      - "5601:5601"
volumes:
  dict-volume:

