version: "3.7"
services:
  mydict:
    build: ./docker/mydict
    volumes:
      - dict-volume:/var/lib/mecab/dic/mydic
  webapp:
    build:
      context: ./webapp
      dockerfile: ../docker/webapp/Dockerfile
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    volumes:
      - ./webapp:/usr/src/app
      - dict-volume:/var/lib/mecab/dic/mydic
    ports:
      - "8088:8088"
    user: $UID:$GID
    links:
      - mongodb
      - fluentd
    depends_on:
      - mongodb
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "onsen-compo.app"
    environment:
      RUST_LOG_STYLE: never
      RUST_LOG: debug
    entrypoint: /bin/bash
    command: "-i"
    tty: true
  mongodb:
    image: mongo:4
    volumes:
      - ./data/mongodb:/data/db
      - ./docker/mongodb:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
  fluentd:
    build: ./docker/fluentd
    volumes:
      - ./docker/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  elasticsearch:
    image: elasticsearch:7.6.2
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.6.2
    links:
      - elasticsearch
    ports:
      - "5601:5601"
volumes:
  dict-volume:

