version: "3.7"
services:
  mydict:
    build: ./docker/mydict
    volumes:
      - dict-volume:/var/lib/mecab/dic/mydic
  webapp:
    build: ./docker/webapp
    volumes:
      - ./webapp:/usr/src
      - app-bin:/target
      - app-data:/data
      - dict-volume:/var/lib/mecab/dic/mydic
    ports:
      - "8088:8088"
    depends_on:
      - elasticsearch
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "onsen-compo.app"
    environment:
      RUST_LOG_STYLE: never
      RUST_LOG: debug
    entrypoint: /bin/bash
    command: "-i"
    tty: true
  cron:
    build: docker/cron
    volumes:
      - app-bin:/app
      - app-data:/data
    depends_on:
      - webapp
  elasticsearch:
    build: docker/elasticsearch
    volumes:
      - es0-data:/usr/share/elasticsearch/data
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
  nginx:
    image: nginx:1-alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/ssl:/etc/ssl
  fluentd:
    image: fluent/fluentd:latest
    volumes:
      - ./docker/fluentd/conf:/fluentd/etc
      - ./logs:/var/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xms256m"
volumes:
  app-bin:
  app-data:
  es0-data:
  dict-volume:

